### ISSUE TITLE
AggregatorV3Interface Part II: latestRoundData

### ISSUE THREAD

**Issue by bh2smith** [cowdao-grants/cow-amm-lp-oracle#11]
Following #10 and utilizing the existing internal helper methods implement `latestRoundData` by 

- retrieve prices from feeds
- simulate order for prices
- simulate pool reserves for order
- determine LP token price
- return the round data

**Comment by lumoswiz** [comment]
In `latesRoundData`, for the `updatedAt` parameter, we are currently (#17 ) returning the update timestamp of the oldest price feed. This gives user's of our price feed knowledge of the oldest feed to make decisions about assessing the staleness of our feed. However, each feed has their own heartbeat which can be different (e.g. 1 hr & 24 hr). This approach potentially loses some information & consumers of the oracle price feed shouldn't have to also monitor the underlying price feeds for assessing staleness.

Discussion point:
- We have unimplemented return parameters from this implementation of `latestRoundData`. In particular, `startedAt` is also a uint256. We could return the update timestamps for both feeds by assigning feed 0 to `startedAt` and feed 1 to `updatedAt`. 
- This would break the expectation that `startedAt` corresponds to "The timestamp when the round started", however, could potentially be useful provided this change is well documented.

@bh2smith let me know what you think of this.

**Comment by bh2smith** [comment]
> @bh2smith let me know what you think of this.

I think we should add this to the Wiki on decisions made for them to evaluate. Done [here](https://github.com/lumoswiz/cow-amm-lp-oracle/wiki/Implementation-Decisions-Log)
Closed by #17
